### ISSUE TITLE
Scale down touch pad by 10-15%

### ISSUE THREAD

**Issue by Dacvak** [AEFeinstein/Super-2024-Swadge-HW#13]

**Comment by AEFeinstein** [comment]
What's the justification here?

**Comment by cnlohr** [comment]
It both feels a tiiiny bit too big to me, and also it's harder to work through the deadzone.  By going to 24mm, and running our fingers around the far outside, we can have better control I feel.

When working on the shroud, be sure to add an edge beyond the size of the spinner, itself.

**Comment by AEFeinstein** [comment]
I'll try to add a reasonable gap between the pad and the acrylic. I'll also be adding a courtyard to the part.
