### ISSUE TITLE
Rev C fixes

### ISSUE THREAD

**Issue by cnlohr** [AEFeinstein/Super-2024-Swadge-HW#15]
Just things I noticed post-submission
- [x] There is still silkscreen under antenna for esp - there should be no silkscreen.
- [x] R3's silkscreen is janked.
- [ ] Adjust C5 silkscreen to not look like "C51"
- [x] Try to hide front-side designator silkscreen under parts or acrylic (MK1, D1, J1)
- [x] We should have? or may (want)? to swap R10, R11 for 5.1k

**Comment by AEFeinstein** [comment]
> There is still silkscreen under antenna for esp - there should be no silkscreen.

Does silkscreen impact RF performance? It's not metal...

**Comment by cnlohr** [comment]
Not appreciably.  sorry, took til now to see this.

**Comment by AEFeinstein** [comment]
Guess we're not changing the I2C pullups

**Comment by cnlohr** [comment]
Sorry, forgot to mention - didn't want to change them.  We were already dropping the mag.

**Comment by AEFeinstein** [comment]
> Adjust C5 silkscreen to not look like "C51"

Moved to #16
