### ISSUE TITLE
Microphone Improvements

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-HW#2]
- [ ] Make sure Elecrow properly solders circuit. Is it possible to make it easier to solder?

**Comment by cnlohr** [comment]
@AEFeinstein can you review:

Current microphone: [C2835889](https://www.lcsc.com/product-detail/Microphones_Goertek-B4013AM423-098_C2835889.html)

Microphone I've been playing with recently: (Is reverse-mount)
[C233789](https://www.lcsc.com/product-detail/MEMS-Microphones_Goertek-S08OB383-031_C233789.html)

**Comment by AEFeinstein** [comment]
The reverse mount is like +$0.07, but otherwise appears to be a microphone. I'm not sure what you want me to review, but if you think the performance is worth the cost, we can at least put pads for it on the first proto.

**Comment by cnlohr** [comment]
I do not feel strongly, but if there was ever a need/desire to have the component be not visible for artistic or other purposes, this is an option.

**Comment by AEFeinstein** [comment]
Oh, if it's for aesthetics, I'm fine with the little button mic. I think that fits well as a detail on the gunship anyway. I'm mostly concerned with solderability, but maybe we can help elecrow out with a better footprint or something.

**Comment by AEFeinstein** [comment]
The microphone on the first prototype didn't work, and this is noted in #11

**Comment by AEFeinstein** [comment]
Mic on the second proto is A-OK
