### ISSUE TITLE
LED Improvements

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-HW#3]
- [x] Investigate acrylic diffuser. Elecrow now has an [acrylic cutting service](https://www.elecrow.com/acrylic-cutting.html). The following materials should be ordered and checked for optical properties
    * 000 - Transparent (probably too clear, engraving adds significant cost)
    * P422 - Matte Transparent (perhaps the only option)
    * 402 - White (check if translucent before ordering)
    * P402 - Matte White (check if translucent before ordering)
- [x] Investigate using cheaper SZLEDCO LEDs

**Comment by AEFeinstein** [comment]
Test parts were ordered, waiting to receive and evaluate them

**Comment by cnlohr** [comment]
Quote has been requested from SZLEDCO

**Comment by AEFeinstein** [comment]
SZLEDCO are great
