### ISSUE TITLE
Touchpad Improvements

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-HW#5]
- [x] Add a circular touchpad

**Comment by AEFeinstein** [comment]
Ideally five interlocking segments around the ring and a sixth pad in the middle

**Comment by AEFeinstein** [comment]
@cnlohr to design ideal shape

**Comment by cnlohr** [comment]
Can we re-use the original footprint from the devkit?
![image](https://github.com/AEFeinstein/Super-2024-Swadge-HW/assets/2748168/95a2975d-e7d3-4a4b-9ecb-ad093843634d)
"Touch Teeth 5"

**Comment by AEFeinstein** [comment]
We sure can use that footprint. It does have one more area than the touch strip, so we'll have to finagle that.
