### ISSUE TITLE
Accelerometer Removal

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-HW#6]
Unless a fair number of games or modes feature accelerometer control, remove it. It's not a great user experience to use it sparingly.

**Comment by cnlohr** [comment]
Can we leave the footprints there and keep it hooked up for the time being and we will decide to pop or nopop later?

**Comment by AEFeinstein** [comment]
Maybe. I don't remember current GPIO usage off the top of my head, but if we want a sixth pad for touch or a second buzzer line, they have to come from somewhere, and that somewhere could be the accel. Assuming GPIOs don't get stolen, I'm fine with just DNPing this

**Comment by cnlohr** [comment]
considering we double-up these pins with the SAO header, that's another strike against that plan.

**Comment by AEFeinstein** [comment]
Still unclear if these get removed or not, but it's covered in #11
