### ISSUE TITLE
Power Circuitry Improvements

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-HW#7]
- [x] Use physically smaller inductor
- [x] Don't place parts too close to battery footprint. The battery clip has some wiggle and can knock passives off

**Comment by cnlohr** [comment]
1. I recommend we continue to use C216158 (2.2uH, 1008 flat package) for the main inductor.
2. I recommend we switch FROM C90317 TO [C6364762](https://www.lcsc.com/product-detail/Power-Inductors_APV-ANR252012T220M_C6364762.html)

**Comment by AEFeinstein** [comment]
@cnlohr I don't think you swapped the inductor. Either do that for the next rev or close this issue please.

**Comment by AEFeinstein** [comment]
Smaller inductors have edges that may catch. Not swapping.
